import {
  IconArrowRight, IconChart, IconCheckSquare, IconDatabase, IconFlask, IconLightning,
  IconPulse, IconRobot, IconShield,
} from "../components/Icons";
import { PageHeader, SectionCard } from "../components/ui";

const KPIS: [string, string][] = [
  ["Denial Rate", "Denied claims ÷ total claims. The single most-watched revenue cycle metric."],
  ["Clean Claim Rate", "Claims paid without denial or rework ÷ total claims — first-pass yield."],
  ["Outstanding A/R", "Allowed − paid − patient responsibility, summed over open claims."],
  ["Revenue at Risk", "Outstanding balances on denied claims plus open claims aged past 60 days."],
  ["A/R Over 90 Days", "Outstanding balance in the 90+ aging bucket — the hardest money to collect."],
  ["Avg Days to Payment", "Mean days from claim submission to payer remittance."],
  ["Preventable Denial Rate", "Share of denials whose category is preventable by front-end process fixes."],
  ["Appeal Success Rate", "Resolved appeals overturned (fully or partially) ÷ resolved appeals."],
  ["Payer Risk Score", "Composite: 50% denial rate + 30% payment lag + 20% share of A/R past 90 days, each normalized to the worst performer."],
];

const TABLES: [string, string][] = [
  ["dim_patient", "1,200 synthetic patients — demographic segments only, no names or identifiers"],
  ["dim_provider", "110 providers with specialty, facility, and clearly fake NPIs"],
  ["dim_facility", "8 care sites (hospital, clinic, ASC, urgent care) across 4 regions"],
  ["dim_payer", "9 payers across Commercial, Medicare, Medicaid, Self-pay, and Other — all fictional names"],
  ["dim_denial_reason", "8 CARC-style denial categories with preventable flags"],
  ["dim_service_line", "7 service lines from Primary Care to Behavioral Health"],
  ["dim_date", "Calendar dimension spanning the activity window"],
  ["fact_claims", "6,000 claims — the hub fact with status, financials, and aging"],
  ["fact_denials", "Denial events with the full appeal lifecycle and recovered dollars"],
  ["fact_payments", "5,000+ remittances with payer-specific payment lags"],
  ["fact_ar_snapshot", "Month-end A/R snapshots with aging buckets"],
  ["fact_followup_tasks", "Tasks generated by the 5-rule automation engine"],
];

const FLOW: [string, string][] = [
  ["Synthetic Data", "Seeded generator — reproducible, zero PHI"],
  ["Python ETL", "Claims, denials, payments, A/R snapshots"],
  ["Star Schema", "CSV extracts + PostgreSQL DDL (7 dims, 5 facts)"],
  ["Validation", "46 automated data-quality gates"],
  ["Automation", "5 business rules → tasks & payer alerts"],
  ["FastAPI", "10 analytics & work-queue endpoints"],
  ["React UI", "This operational dashboard"],
  ["Power BI", "Executive reporting layer (documented DAX)"],
];

const PROVES: { icon: React.ReactNode; title: string; sub: string }[] = [
  { icon: <IconDatabase size={16} />, title: "SQL data modeling", sub: "Kimball star schema with keys, constraints, and indexes" },
  { icon: <IconFlask size={16} />, title: "Python ETL", sub: "Deterministic, modular pipeline with logging and error handling" },
  { icon: <IconPulse size={16} />, title: "Revenue cycle analytics", sub: "Denials, A/R aging, payer scorecards, appeal recovery" },
  { icon: <IconLightning size={16} />, title: "API development", sub: "FastAPI with typed models, filtering, and Swagger docs" },
  { icon: <IconChart size={16} />, title: "React dashboarding", sub: "TypeScript, componentized UI, live API data" },
  { icon: <IconRobot size={16} />, title: "Workflow automation", sub: "Idempotent rules engine that turns analytics into work" },
  { icon: <IconCheckSquare size={16} />, title: "Data quality engineering", sub: "46-check validation suite gating every pipeline run" },
  { icon: <IconShield size={16} />, title: "BI storytelling", sub: "Documented Power BI pages and DAX measure library" },
];

export default function About() {
  return (
    <>
      <PageHeader
        title="About & Data Dictionary"
        subtitle="What this system is, how the data flows, and how every number on the other pages is defined."
      />

      <div className="callout warn" style={{ marginBottom: 18 }}>
        <span className="co-icon">
          <IconShield size={17} />
        </span>
        <div>
          <strong>Synthetic data disclaimer:</strong> this project uses synthetic/public-style healthcare
          data only and does not contain real patient information. Every patient, provider, payer, and claim
          is generated programmatically with a fixed random seed (42). All organization names are fictional
          and NPIs are fake by construction.
        </div>
      </div>

      <SectionCard
        title="How the Data Flows"
        sub="From seeded generator to the dashboards — every stage is a real, runnable component in the repository"
      >
        <div className="arch-flow">
          {FLOW.map(([title, sub], i) => (
            <div key={title} style={{ display: "contents" }}>
              <div className="arch-node">
                <div className="a-step">Step {i + 1}</div>
                <div className="a-title">{title}</div>
                <div className="a-sub">{sub}</div>
              </div>
              {i < FLOW.length - 1 && (
                <span className="arch-arrow">
                  <IconArrowRight size={14} />
                </span>
              )}
            </div>
          ))}
        </div>
      </SectionCard>

      <div className="grid two-col" style={{ marginTop: 16 }}>
        <SectionCard title="What This Is">
          <p style={{ fontSize: 13.5, marginTop: 0 }}>
            The <strong>Healthcare Revenue Cycle Command Center</strong> is an end-to-end analytics and
            automation platform: a deterministic synthetic claims dataset, a PostgreSQL star schema, a
            Python ETL and validation pipeline, documented analytics SQL, an automation rules engine that
            turns analytics into prioritized work, this React operational dashboard, and a documented Power
            BI reporting layer.
          </p>
          <p style={{ fontSize: 13.5, marginBottom: 0 }}>
            It answers the questions revenue cycle teams ask every morning: which claims were denied and
            why, which payers need escalation, how much revenue is at risk, what is aging past 90 days, and
            what should be worked <em>first</em>.
          </p>
        </SectionCard>

        <SectionCard title="KPI Definitions" sub="The exact logic behind every headline number">
          <table>
            <tbody>
              {KPIS.map(([name, def]) => (
                <tr key={name}>
                  <td style={{ fontWeight: 650, whiteSpace: "nowrap", verticalAlign: "top", paddingLeft: 0 }}>
                    {name}
                  </td>
                  <td style={{ fontSize: 12.5, color: "var(--text-dim)", paddingRight: 0 }}>{def}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </SectionCard>
      </div>

      <div className="section-title">What This Project Demonstrates</div>
      <div className="prove-grid">
        {PROVES.map((p) => (
          <div className="prove-item" key={p.title}>
            <span className="p-icon">{p.icon}</span>
            <div>
              <div className="p-title">{p.title}</div>
              <div className="p-sub">{p.sub}</div>
            </div>
          </div>
        ))}
      </div>

      <div className="section-title">Star Schema Tables</div>
      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Table</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            {TABLES.map(([name, desc]) => (
              <tr key={name}>
                <td className="mono" style={{ whiteSpace: "nowrap", fontWeight: 600 }}>{name}</td>
                <td style={{ color: "var(--text-dim)" }}>{desc}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p style={{ fontSize: 12.5, color: "var(--text-faint)", marginTop: 18 }}>
        Full column-level documentation lives in <span className="mono">database/data_dictionary.md</span>{" "}
        in the repository, alongside the case study, architecture diagrams, and Power BI documentation.
      </p>
    </>
  );
}
