const KPIS: [string, string][] = [
  ["Denial Rate", "Denied claims ÷ total claims. The single most-watched revenue cycle metric."],
  ["Clean Claim Rate", "Claims paid without denial or rework ÷ total claims — first-pass yield."],
  ["Outstanding A/R", "Allowed − paid − patient responsibility, summed over open claims."],
  ["Revenue at Risk", "Outstanding balances on denied claims plus open claims aged past 60 days."],
  ["A/R Over 90 Days", "Outstanding balance in the 90+ aging bucket — the hardest money to collect."],
  ["Avg Days to Payment", "Mean days from claim submission to payer remittance."],
  ["Preventable Denial Rate", "Share of denials whose category is preventable by front-end process fixes."],
  ["Appeal Success Rate", "Resolved appeals overturned (fully or partially) ÷ resolved appeals."],
  ["Payer Risk Score", "Composite: 50% denial rate + 30% payment lag + 20% share of A/R past 90 days, each normalized to the worst performer."],
];

const TABLES: [string, string][] = [
  ["dim_patient", "1,200 synthetic patients — demographic segments only, no names or identifiers"],
  ["dim_provider", "110 providers with specialty, facility, and clearly fake NPIs"],
  ["dim_facility", "8 care sites (hospital, clinic, ASC, urgent care) across 4 regions"],
  ["dim_payer", "9 payers across Commercial, Medicare, Medicaid, Self-pay, and Other"],
  ["dim_denial_reason", "8 CARC-style denial categories with preventable flags"],
  ["dim_service_line", "7 service lines from Primary Care to Behavioral Health"],
  ["dim_date", "Calendar dimension spanning the activity window"],
  ["fact_claims", "6,000 claims — the hub fact with status, financials, and aging"],
  ["fact_denials", "Denial events with the full appeal lifecycle and recovered dollars"],
  ["fact_payments", "5,000+ remittances with payer-specific payment lags"],
  ["fact_ar_snapshot", "Month-end A/R snapshots with aging buckets"],
  ["fact_followup_tasks", "Tasks generated by the 5-rule automation engine"],
];

export default function About() {
  return (
    <>
      <div className="page-header">
        <h1>About &amp; Data Dictionary</h1>
        <div className="desc">What this system is, what the data is, and how the numbers are defined.</div>
      </div>

      <div className="callout warn" style={{ marginBottom: 16 }}>
        <strong>Synthetic data disclaimer:</strong> this project uses synthetic/public-style healthcare data
        only and does not contain real patient information. Every patient, provider, payer, and claim is
        generated programmatically with a fixed random seed (42). NPIs are fake by construction.
      </div>

      <div className="grid two-col">
        <div className="card">
          <h3>What This Is</h3>
          <p style={{ fontSize: 13.5 }}>
            The <strong>Healthcare Revenue Cycle Command Center</strong> is an end-to-end portfolio project:
            a deterministic synthetic claims dataset, a PostgreSQL star schema, a Python ETL and validation
            pipeline, documented analytics SQL, an automation rules engine that turns analytics into
            prioritized work, this React operational dashboard, and a documented Power BI reporting layer.
          </p>
          <p style={{ fontSize: 13.5 }}>
            It answers the questions revenue cycle teams ask every morning: which claims were denied and why,
            which payers need escalation, how much revenue is at risk, what is aging past 90 days, and what
            should be worked <em>first</em>.
          </p>
          <h3 style={{ marginTop: 18 }}>Architecture</h3>
          <p style={{ fontSize: 13.5, marginBottom: 6 }}>
            <span className="mono">
              Python generator → ETL pipeline → CSV star schema (+ optional PostgreSQL) → analytics SQL +
              rules engine → FastAPI → this React UI (and Power BI for executives)
            </span>
          </p>
          <h3 style={{ marginTop: 18 }}>Tools Used</h3>
          <p style={{ fontSize: 13.5 }}>
            Python (pandas), PostgreSQL DDL with Docker Compose, FastAPI + Pydantic, React 18 + TypeScript +
            Vite, Recharts, documented DAX measures for Power BI, and a 46-check data validation suite.
          </p>
        </div>

        <div className="card">
          <h3>KPI Definitions</h3>
          <table>
            <tbody>
              {KPIS.map(([name, def]) => (
                <tr key={name}>
                  <td style={{ fontWeight: 600, whiteSpace: "nowrap", verticalAlign: "top" }}>{name}</td>
                  <td style={{ fontSize: 12.5, color: "var(--text-dim)" }}>{def}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="section-title">Star Schema Tables</div>
      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Table</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            {TABLES.map(([name, desc]) => (
              <tr key={name}>
                <td className="mono" style={{ whiteSpace: "nowrap" }}>{name}</td>
                <td style={{ color: "var(--text-dim)" }}>{desc}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p style={{ fontSize: 12.5, color: "var(--text-faint)", marginTop: 18 }}>
        Full column-level documentation lives in <span className="mono">database/data_dictionary.md</span> in
        the repository, alongside the case study, architecture diagrams, and Power BI documentation.
      </p>
    </>
  );
}
