import { useState } from "react";
import { Link } from "react-router-dom";
import { api, fmtDate, fmtMoney, fmtNum } from "../api/client";
import {
  EmptyState, ErrorState, Filter, FilterBar, Loading, MetricCard, PageHeader, PriorityBadge,
  TaskStatusBadge, useFetch,
} from "../components/ui";
import { IconAlert, IconCheckSquare, IconClock, IconInbox } from "../components/Icons";
import type { TaskList } from "../api/types";

const PAGE_SIZE = 25;
const TEAMS = ["Denials Team", "AR Follow-up Team", "Documentation Team", "Appeals Team"];
const STATUSES = ["Open", "In Progress", "Completed", "Cancelled"];
const PRIORITIES = ["Urgent", "High", "Medium", "Low"];

export default function Tasks() {
  const [status, setStatus] = useState("");
  const [priority, setPriority] = useState("");
  const [team, setTeam] = useState("");
  const [overdueOnly, setOverdueOnly] = useState(false);
  const [page, setPage] = useState(0);

  const tasks = useFetch<TaskList>(
    () =>
      api.tasks({
        status, priority, team,
        overdue_only: overdueOnly || undefined,
        limit: PAGE_SIZE,
        offset: page * PAGE_SIZE,
      }),
    [status, priority, team, overdueOnly, page],
  );

  const reset = () => setPage(0);

  return (
    <>
      <PageHeader
        title="Follow-Up Tasks"
        subtitle="The work management board — every task was generated by the automation rules engine, one per claim per rule, with SLA due dates set by priority."
      />

      {tasks.data && (
        <div className="grid kpi-grid" style={{ marginBottom: 16 }}>
          <MetricCard
            label="Open"
            value={fmtNum(tasks.data.summary.open)}
            context="Waiting to be picked up"
            icon={<IconInbox size={16} />}
            tone="blue"
          />
          <MetricCard
            label="In Progress"
            value={fmtNum(tasks.data.summary.in_progress)}
            context="Being worked now"
            icon={<IconClock size={16} />}
            tone="teal"
          />
          <MetricCard
            label="Overdue"
            value={fmtNum(tasks.data.summary.overdue)}
            context="Past SLA due date"
            icon={<IconAlert size={16} />}
            tone="red"
          />
          <MetricCard
            label="Completed"
            value={fmtNum(tasks.data.summary.completed)}
            context={`Avg ${tasks.data.summary.avg_days_to_close ?? "—"} days to close`}
            icon={<IconCheckSquare size={16} />}
            tone="green"
          />
        </div>
      )}

      <FilterBar>
        <Filter label="Status">
          <select value={status} onChange={(e) => { setStatus(e.target.value); reset(); }}>
            <option value="">All statuses</option>
            {STATUSES.map((s) => <option key={s}>{s}</option>)}
          </select>
        </Filter>
        <Filter label="Priority">
          <select value={priority} onChange={(e) => { setPriority(e.target.value); reset(); }}>
            <option value="">All priorities</option>
            {PRIORITIES.map((p) => <option key={p}>{p}</option>)}
          </select>
        </Filter>
        <Filter label="Assigned team">
          <select value={team} onChange={(e) => { setTeam(e.target.value); reset(); }}>
            <option value="">All teams</option>
            {TEAMS.map((t) => <option key={t}>{t}</option>)}
          </select>
        </Filter>
        <button
          className={`btn${overdueOnly ? " btn-active" : ""}`}
          onClick={() => { setOverdueOnly((v) => !v); reset(); }}
        >
          {overdueOnly ? "✓ " : ""}Overdue only
        </button>
      </FilterBar>

      {tasks.loading && <Loading label="Loading tasks…" />}
      {tasks.error && <ErrorState message={tasks.error} />}
      {tasks.data && tasks.data.items.length === 0 && (
        <EmptyState title="No tasks match these filters" hint="The queue is clear for this slice." />
      )}

      {tasks.data && tasks.data.items.length > 0 && (
        <>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Task</th>
                  <th>Claim</th>
                  <th>Payer</th>
                  <th className="num">Outstanding</th>
                  <th>Priority</th>
                  <th>Team</th>
                  <th>Due</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {tasks.data.items.map((t) => (
                  <tr key={t.task_id} className={t.is_overdue ? "risk-row" : ""}>
                    <td>
                      <span className="cell-main">{t.task_type}</span>
                      <div className="cell-sub" style={{ maxWidth: 330 }}>{t.reason}</div>
                    </td>
                    <td>
                      <Link className="mono" style={{ fontWeight: 650 }} to={`/claims/${t.claim_id}`}>
                        {t.claim_id}
                      </Link>
                    </td>
                    <td>{t.payer_name ?? "—"}</td>
                    <td className="num">{fmtMoney(t.outstanding_amount)}</td>
                    <td><PriorityBadge priority={t.priority} /></td>
                    <td>{t.assigned_team}</td>
                    <td>
                      <span style={t.is_overdue ? { color: "var(--red)", fontWeight: 650 } : undefined}>
                        {fmtDate(t.due_date)}
                      </span>
                      {t.is_overdue && <span className="badge red" style={{ marginLeft: 6 }}>Overdue</span>}
                    </td>
                    <td><TaskStatusBadge status={t.status} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="pagination">
            <span>
              {fmtNum(page * PAGE_SIZE + 1)}–{fmtNum(Math.min((page + 1) * PAGE_SIZE, tasks.data.total))} of{" "}
              {fmtNum(tasks.data.total)} tasks
            </span>
            <button className="btn" disabled={page === 0} onClick={() => setPage((p) => p - 1)}>
              ← Prev
            </button>
            <button
              className="btn"
              disabled={(page + 1) * PAGE_SIZE >= tasks.data.total}
              onClick={() => setPage((p) => p + 1)}
            >
              Next →
            </button>
          </div>
        </>
      )}
    </>
  );
}
