import { useState } from "react";
import { Link } from "react-router-dom";
import { api, fmtDate, fmtMoney, fmtNum } from "../api/client";
import {
  EmptyState, ErrorState, Loading, PriorityBadge, TaskStatusBadge, useFetch,
} from "../components/ui";
import type { TaskList } from "../api/types";

const PAGE_SIZE = 25;
const TEAMS = ["Denials Team", "AR Follow-up Team", "Documentation Team", "Appeals Team"];
const STATUSES = ["Open", "In Progress", "Completed", "Cancelled"];
const PRIORITIES = ["Urgent", "High", "Medium", "Low"];

export default function Tasks() {
  const [status, setStatus] = useState("");
  const [priority, setPriority] = useState("");
  const [team, setTeam] = useState("");
  const [overdueOnly, setOverdueOnly] = useState(false);
  const [page, setPage] = useState(0);

  const tasks = useFetch<TaskList>(
    () =>
      api.tasks({
        status, priority, team,
        overdue_only: overdueOnly || undefined,
        limit: PAGE_SIZE,
        offset: page * PAGE_SIZE,
      }),
    [status, priority, team, overdueOnly, page],
  );

  const reset = () => setPage(0);

  return (
    <>
      <div className="page-header">
        <h1>Follow-Up Tasks</h1>
        <div className="desc">
          Work generated by the automation rules engine — one task per claim per rule, SLA due dates by priority.
        </div>
      </div>

      {tasks.data && (
        <div className="grid kpi-grid" style={{ marginBottom: 16 }}>
          <div className="kpi-card">
            <div className="label">Open</div>
            <div className="value">{fmtNum(tasks.data.summary.open)}</div>
          </div>
          <div className="kpi-card">
            <div className="label">In Progress</div>
            <div className="value">{fmtNum(tasks.data.summary.in_progress)}</div>
          </div>
          <div className="kpi-card tone-red">
            <div className="label">Overdue</div>
            <div className="value">{fmtNum(tasks.data.summary.overdue)}</div>
          </div>
          <div className="kpi-card tone-green">
            <div className="label">Completed</div>
            <div className="value">{fmtNum(tasks.data.summary.completed)}</div>
          </div>
          <div className="kpi-card">
            <div className="label">Avg Days to Close</div>
            <div className="value">{tasks.data.summary.avg_days_to_close ?? "—"}</div>
          </div>
        </div>
      )}

      <div className="filter-bar">
        <div className="filter">
          <label>Status</label>
          <select value={status} onChange={(e) => { setStatus(e.target.value); reset(); }}>
            <option value="">All statuses</option>
            {STATUSES.map((s) => <option key={s}>{s}</option>)}
          </select>
        </div>
        <div className="filter">
          <label>Priority</label>
          <select value={priority} onChange={(e) => { setPriority(e.target.value); reset(); }}>
            <option value="">All priorities</option>
            {PRIORITIES.map((p) => <option key={p}>{p}</option>)}
          </select>
        </div>
        <div className="filter">
          <label>Assigned team</label>
          <select value={team} onChange={(e) => { setTeam(e.target.value); reset(); }}>
            <option value="">All teams</option>
            {TEAMS.map((t) => <option key={t}>{t}</option>)}
          </select>
        </div>
        <button
          className="btn"
          style={overdueOnly ? { borderColor: "var(--red)", color: "var(--red)" } : undefined}
          onClick={() => { setOverdueOnly((v) => !v); reset(); }}
        >
          {overdueOnly ? "✓ " : ""}Overdue only
        </button>
      </div>

      {tasks.loading && <Loading label="Loading tasks…" />}
      {tasks.error && <ErrorState message={tasks.error} />}
      {tasks.data && tasks.data.items.length === 0 && (
        <EmptyState title="No tasks match these filters" hint="The queue is clear for this slice." />
      )}

      {tasks.data && tasks.data.items.length > 0 && (
        <>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Task</th>
                  <th>Claim</th>
                  <th>Payer</th>
                  <th className="num">Outstanding</th>
                  <th>Priority</th>
                  <th>Team</th>
                  <th>Due</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {tasks.data.items.map((t) => (
                  <tr key={t.task_id} className={t.is_overdue ? "risk-row" : ""}>
                    <td>
                      <strong style={{ fontSize: 13 }}>{t.task_type}</strong>
                      <div style={{ fontSize: 11.5, color: "var(--text-faint)", maxWidth: 320 }}>{t.reason}</div>
                    </td>
                    <td>
                      <Link className="mono" to={`/claims/${t.claim_id}`}>{t.claim_id}</Link>
                    </td>
                    <td>{t.payer_name ?? "—"}</td>
                    <td className="num">{fmtMoney(t.outstanding_amount)}</td>
                    <td><PriorityBadge priority={t.priority} /></td>
                    <td>{t.assigned_team}</td>
                    <td>
                      {fmtDate(t.due_date)}
                      {t.is_overdue && <span className="badge red" style={{ marginLeft: 6 }}>Overdue</span>}
                    </td>
                    <td><TaskStatusBadge status={t.status} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="pagination">
            <span>
              {fmtNum(page * PAGE_SIZE + 1)}–{fmtNum(Math.min((page + 1) * PAGE_SIZE, tasks.data.total))} of{" "}
              {fmtNum(tasks.data.total)} tasks
            </span>
            <button className="btn" disabled={page === 0} onClick={() => setPage((p) => p - 1)}>
              ← Prev
            </button>
            <button
              className="btn"
              disabled={(page + 1) * PAGE_SIZE >= tasks.data.total}
              onClick={() => setPage((p) => p + 1)}
            >
              Next →
            </button>
          </div>
        </>
      )}
    </>
  );
}
